name: Cleanup untagged images

on:
  workflow_run:
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  clean:
    name: Delete untagged images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          owner: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          package: ${{ github.event.repository.name }}
          delete-untagged: true
          dry-run: true
