name: PR Workflow

on:
  pull_request:
    branches: [development, release-*]

jobs:
  run_tests:
    uses: tataranovich/ai-dial-ci/.github/workflows/java_pr.yml@arm64-builds
    secrets: inherit
    with:
      platforms: "linux/amd64,linux/arm64"
