name: Release Workflow

on:
  push:
    branches: [development, release-*]

jobs:
  release:
    uses: tataranovich/ai-dial-ci/.github/workflows/java_release.yml@arm64-builds
    secrets: inherit
    with:
      platforms: "linux/amd64,linux/arm64"
      code-checks-enabled: false
      ort-enabled: false
