name: Release Workflow

on:
  push:
    branches: [development, release-*]

jobs:
  release:
    uses: epam/ai-dial-ci/.github/workflows/java_release.yml@1.12.1
    secrets:
      ACTIONS_BOT_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
