name: Release Workflow

on:
  push:
    branches: [development, release-*]

jobs:
  release:
    uses: tataranovich/ai-dial-ci/.github/workflows/java_release.yml@main
    with:
      enable_style_checks: false
      enable_code_checks: false
      enable_ort: false
      enable_trivy: false
    secrets: inherit
